# Generated by Django 3.2.11 on 2022-01-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infected_percent', models.CharField(max_length=15)),
                ('non_infected_percent', models.CharField(max_length=15)),
                ('avg_water', models.CharField(max_length=15)),
                ('avg_food', models.CharField(max_length=15)),
                ('avg_first_aid', models.CharField(max_length=15)),
                ('avg_gun', models.CharField(max_length=15)),
                ('lost_points', models.CharField(max_length=15)),
                ('report_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(blank=True, max_length=1)),
                ('last_location_lat', models.DecimalField(decimal_places=4, max_digits=6)),
                ('last_location_long', models.DecimalField(decimal_places=4, max_digits=6)),
                ('fiji_water', models.IntegerField(blank=True)),
                ('campbell_soup', models.IntegerField(blank=True)),
                ('first_aid_pouch', models.IntegerField(blank=True)),
                ('ak_47', models.IntegerField(blank=True)),
                ('infection', models.CharField(default=False, editable=False, max_length=3)),
                ('infection_count', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='SurvivorTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survivor_1_id', models.IntegerField(blank=True)),
                ('survivor_2_id', models.IntegerField(blank=True)),
                ('survivor_1_water', models.IntegerField(blank=True)),
                ('survivor_1_soup', models.IntegerField(blank=True)),
                ('survivor_1_first_aid', models.IntegerField(blank=True)),
                ('survivor_1_gun', models.IntegerField(blank=True)),
                ('survivor_2_water', models.IntegerField(blank=True)),
                ('survivor_2_soup', models.IntegerField(blank=True)),
                ('survivor_2_first_aid', models.IntegerField(blank=True)),
                ('survivor_2_gun', models.IntegerField(blank=True)),
            ],
        ),
    ]
